baseurl = "/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "Mainroad"
[Author]
avatar = "img/avatar.png"
bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
name = "John Doe"
[Params]
authorbox = true
description = "John Doe's Personal blog about everything"
opengraph = true
post_meta = ["date", "categories"]
post_navigation = true
readmore = false
subtitle = "Just another site"
twitter_cards = false
[Params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["search", "recent", "categories", "taglist"]
[Params.widgets]
recent_num = 5
tags_counter = false
